version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - database/.env
    ports:
      - '5001:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/create.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./database/insert.sql:/docker-entrypoint-initdb.d/fill_tables.sql
  app:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: development
    ports:
      - "5000:5000"
    command: npm run dev
    volumes:
      - .:/src/
      - /src/node_modules
volumes:
  db:
    driver: local
