version: '3.8'
services:
    db:
        image: postgres:14.2-alpine
        restart: always
        env_file:
            - database/.env
        ports:
            - '5433:5432'
        volumes:
            - db:/var/lib/postgresql/data
            - ./database/create.sql:/docker-entrypoint-initdb.d/create_tables.sql
            - ./database/insert.sql:/docker-entrypoint-initdb.d/fill_tables.sql
volumes:
    db:
        driver: local
