DROP TABLE QUESTIONS;
DROP TABLE CATEGORIES;
DROP TABLE PRIVATE_GAMES_STATE;
DROP TABLE USER_PRIVATE_GAMES;
DROP TABLE PRIVATE_GAME;
DROP TABLE PUBLIC_GAMES_STATE;
DROP TABLE USER_PUBLIC_GAMES;
DROP TABLE PUBLIC_GAME;
DROP TABLE INDIVIDUAL_GAME;
DROP TABLE USER_ACHIEVEMENTS;
DROP TABLE USER_WILDCARDS;
DROP TABLE USER_COSMETICS;
DROP TABLE FRIENDS;
DROP TABLE USERS;
DROP TABLE ACHIEVEMENTS;
DROP TABLE WILDCARDS;
DROP TABLE COSMETICS;



