INSERT INTO CATEGORIES VALUES('Entertainment');
INSERT INTO CATEGORIES VALUES('Science');
INSERT INTO CATEGORIES VALUES('History');
INSERT INTO CATEGORIES VALUES('Sports');
INSERT INTO CATEGORIES VALUES('Geography');
INSERT INTO CATEGORIES VALUES('Art');